/**
 * Create and cancel bookings.
 *
 * The appliance has no API for either — both go through the same Struts forms
 * a browser uses, verified live end-to-end in the Phase 0 spike (create a
 * booking, confirm it via `get_bookings`, delete it, confirm it's gone). This
 * module is that spike turned into something the relay can call.
 *
 * Create:
 *   GET  BookingForm.action?display_date=&start_time=&end_time=   (session cookie + field defaults)
 *   POST saveBooking.action                                       (full form, our fields overridden)
 *   -> 302 to GroupView.action means accepted; 200 means rejected, form re-rendered
 *
 * Cancel:
 *   GET  BookingForm.action?booking_id=&display_date=
 *   POST validateBookingPassword.action   (password added)        -> showDeleteButton=true means accepted
 *   POST populateDelete.action            (fields carried forward) -> confirmation page
 *   POST deleteBooking.action             (fields carried forward) -> 302 to GroupView.action means deleted
 *
 * Every POST must carry the *entire* previous form, not just the fields we
 * changed — the appliance rejects a partial body. `ApplianceSession` keeps the
 * cookie; `parseFormFields` + a spread override is what carries the rest.
 */

import { randomBytes } from "node:crypto";
import { ApplianceSession } from "./session.ts";
import { BOOKING_DEFAULTS, extractFormError, parseFormFields, type FormFields } from "./forms.ts";
import { fetchBookings, type RawBooking } from "./roomwizard.ts";
import type { Room } from "./rooms.ts";
import {
  fromFormDateParts,
  parseApplianceTimestamp,
  toApplianceDate,
  toApplianceTime,
  toFormDateParts,
  toIso,
  type Instant,
} from "./time.ts";

export class BookingValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BookingValidationError";
  }
}

/** The appliance understood the request and said no — wrong password, etc. */
export class BookingRejectedError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BookingRejectedError";
  }
}

export interface CreateBookingArgs {
  room: Room;
  start: Instant;
  end: Instant;
  purpose: string;
  hostFirstName: string;
  hostLastName: string;
  /**
   * Optional. Verified live that the appliance persists and echoes this back
   * even though its own UI never renders a visible input for it on this
   * install (the form field is present, just hidden — `showEmail=false`).
   * Not verified: the `user1`/`user2`/`user3` invitee fields, which the form
   * also carries but which left no trace in a follow-up `get_bookings` read
   * after being set — likely meaningless without the LDAP integration this
   * install doesn't have configured. Deliberately not exposed here.
   */
  hostEmail?: string;
  /** Generated by the caller if omitted — see `generateBookingPassword`. */
  password: string;
}

export interface CreatedBooking {
  id: string;
  roomId: string;
  start: string;
  end: string;
  purpose: string;
  /**
   * Returned exactly once, here. The relay is stateless and does not keep it;
   * the caller (ultimately the browser) must hold onto this to cancel later.
   * See PLAN.md section 7 on why we generate this ourselves rather than
   * leaving a booking unprotected.
   */
  password: string;
}

/** A booking password strong enough to resist offline guessing. See PLAN.md section 7. */
export function generateBookingPassword(): string {
  return randomBytes(18).toString("base64url");
}

/** Does an appliance response amount to "accepted"? Pure, so it's testable without a live appliance. */
export function isAcceptedRedirect(res: { status: number; location: string | null }): boolean {
  return res.status >= 300 && res.status < 400 && (res.location ?? "").includes("GroupView");
}

export async function createBooking(args: CreateBookingArgs): Promise<CreatedBooking> {
  const { room, start, end, purpose, hostFirstName, hostLastName, hostEmail, password } = args;
  const session = new ApplianceSession(room.host);

  const formRes = await session.get("BookingForm.action", {
    display_date: toApplianceDate(start),
    start_time: toApplianceTime(start),
    end_time: toApplianceTime(end),
  });
  const base = parseFormFields(formRes.body);
  const startParts = toFormDateParts(start);
  const endParts = toFormDateParts(end);

  const submission: FormFields = {
    ...base,
    ...BOOKING_DEFAULTS,
    booking_id: "",
    purpose,
    hostFirstName,
    hostLastName,
    hostEmail: hostEmail ?? "",
    password,
    repeatPassword: password,
    start_time: toApplianceTime(start),
    end_time: toApplianceTime(end),
    startTime: toApplianceTime(start),
    startDate: startParts.day,
    startMonth: startParts.yearMonth,
    endTime: toApplianceTime(end),
    endDate: endParts.day,
    endMonth: endParts.yearMonth,
  };

  const saveRes = await session.postForm("saveBooking.action", submission);

  if (!isAcceptedRedirect(saveRes)) {
    const error = extractFormError(parseFormFields(saveRes.body));
    throw new BookingRejectedError(
      error ?? `The room system did not accept the booking (HTTP ${saveRes.status})`,
    );
  }

  const raw = await fetchBookings(room.host, start, end);
  const created = matchCreatedBooking(raw, start, end, purpose);
  if (!created) {
    // The appliance accepted it (we got the redirect) but we couldn't find it
    // on re-read — e.g. the Connector's eventual-consistency window, or
    // something stranger. Surface this distinctly: it means the room may now
    // actually be booked but we have no id to hand back for cancellation.
    throw new BookingRejectedError(
      "The booking was accepted but could not be confirmed afterwards. Check the room's schedule directly before retrying.",
    );
  }

  return { ...created, roomId: room.id, password };
}

/**
 * Pick the booking we just created out of a room's booking list.
 *
 * The appliance's redirect confirms acceptance but carries no booking id, so
 * re-reading the room is the only way to get one back. Several bookings can
 * share an exact start/end if two were raced in close together (the
 * appliance does nothing to prevent that — see PLAN.md section 6), so an
 * exact purpose match is preferred, falling back to the most recently
 * created. Pure and exported so this tie-breaking can be tested directly
 * against fixtures rather than only against a live appliance.
 */
export function matchCreatedBooking(
  raw: readonly RawBooking[],
  start: Instant,
  end: Instant,
  purpose: string,
): Pick<CreatedBooking, "id" | "start" | "end" | "purpose"> | null {
  const startMs = start.getTime();
  const endMs = end.getTime();

  // Appliance timestamps carry no offset, so they must go through
  // parseApplianceTimestamp (which interprets them in the fleet's configured
  // zone) rather than Date.parse — Date.parse resolves an offset-less string
  // against the *process's* system timezone, which is an environment detail
  // that has nothing to do with where the appliance is installed. On a Mac
  // whose system zone happens to be America/Phoenix this bug is invisible;
  // under the project's own Dockerfile (node:22-alpine, system TZ=UTC) it
  // would make every real success look like "accepted but could not be
  // confirmed". Caught by CI running on a UTC runner, not by local testing.
  const candidates = raw.filter((b) => {
    try {
      return (
        parseApplianceTimestamp(b.start).getTime() === startMs &&
        parseApplianceTimestamp(b.end).getTime() === endMs
      );
    } catch {
      return false;
    }
  });
  if (candidates.length === 0) return null;

  const exact = candidates.find((b) => b.purpose === purpose);
  const chosen =
    exact ??
    candidates.reduce((latest, b) =>
      (b.creationDate ?? "") > (latest.creationDate ?? "") ? b : latest,
    );

  return {
    id: String(chosen.Id),
    start: toIso(parseApplianceTimestamp(chosen.start)),
    end: toIso(parseApplianceTimestamp(chosen.end)),
    purpose: chosen.purpose,
  };
}

/**
 * Verified live on a disposable booking: `updateBooking.action` is a sibling
 * of `saveBooking.action`, reached through the same password-gated flow as
 * cancellation (`BookingForm.action?booking_id=` -> `validateBookingPassword.action`,
 * which both unlocks `showDeleteButton` AND re-renders the form with the
 * booking's real current values -- purpose, name, email, time -- which are
 * otherwise hidden from anyone who hasn't proven they know the password).
 *
 * Also verified: leaving `password`/`repeatPassword` as whatever the
 * validated form carries (blank -- the appliance never echoes a password
 * back) preserves the existing password rather than clearing it. Confirmed
 * by cancelling with the *original* password after an edit and watching it
 * still work.
 */
export interface UpdateBookingArgs {
  room: Room;
  bookingId: string;
  /** The booking's current password. Required to reach the editable form at all. */
  currentPassword: string;
  start: Instant;
  end: Instant;
  purpose: string;
  hostFirstName: string;
  hostLastName: string;
  hostEmail?: string;
}

/**
 * Load a booking by id and prove we know its password, returning the form
 * fields the appliance reveals once that's confirmed -- the real current
 * purpose/name/email/time, which stay blank until this step succeeds. Shared
 * by `updateBooking` and `cancelBooking`, which otherwise diverge only in
 * what they do with an already-authenticated session.
 */
export async function validateBookingAccess(
  session: ApplianceSession,
  room: Room,
  bookingId: string,
  password: string,
): Promise<FormFields> {
  const formRes = await session.get("BookingForm.action", { booking_id: bookingId });
  const loaded = parseFormFields(formRes.body);
  if (!loaded.booking_id) {
    throw new BookingValidationError(`No booking ${bookingId} found on ${room.id}`);
  }

  const validateRes = await session.postForm("validateBookingPassword.action", {
    ...loaded,
    password,
  });
  const validated = parseFormFields(validateRes.body);
  if (validated.showDeleteButton !== "true") {
    throw new BookingRejectedError("Incorrect booking password");
  }
  return validated;
}

/**
 * One attempt at validate -> submit -> confirm. Pulled out of `updateBooking`
 * so it can be retried wholesale with a brand new session.
 */
async function attemptUpdate(args: UpdateBookingArgs): Promise<boolean> {
  const { room, bookingId, currentPassword, start, end, purpose, hostFirstName, hostLastName, hostEmail } =
    args;
  const session = new ApplianceSession(room.host);
  const validated = await validateBookingAccess(session, room, bookingId, currentPassword);

  const startParts = toFormDateParts(start);
  const endParts = toFormDateParts(end);
  const submission: FormFields = {
    ...validated,
    ...BOOKING_DEFAULTS,
    booking_id: bookingId,
    purpose,
    hostFirstName,
    hostLastName,
    hostEmail: hostEmail ?? "",
    start_time: toApplianceTime(start),
    end_time: toApplianceTime(end),
    startTime: toApplianceTime(start),
    startDate: startParts.day,
    startMonth: startParts.yearMonth,
    endTime: toApplianceTime(end),
    endDate: endParts.day,
    endMonth: endParts.yearMonth,
  };

  const updateRes = await session.postForm("updateBooking.action", submission);
  if (!isAcceptedRedirect(updateRes)) {
    const error = extractFormError(parseFormFields(updateRes.body));
    throw new BookingRejectedError(
      error ?? `The room system did not accept the change (HTTP ${updateRes.status})`,
    );
  }

  // The appliance's redirect is not reliable proof the write actually took.
  // Observed live: a validate-then-update sequence can get an accepted
  // redirect while the booking's fields are left completely unchanged --
  // most likely the appliance's own session handling under concurrent
  // requests to the same booking (the picker polls availability in the
  // background while an edit is open), something this relay can observe but
  // not fix on the appliance's side. Re-reading and comparing is the only way
  // to tell a real success from a silently swallowed one.
  const raw = await fetchBookings(room.host, start, end);
  const current = raw.find((b) => String(b.Id) === bookingId);
  return current !== undefined && current.purpose === purpose;
}

export async function updateBooking(args: UpdateBookingArgs): Promise<void> {
  if (await attemptUpdate(args)) return;
  // One retry with a fresh session before giving up -- cheap, and the
  // failure mode above has only ever been observed to need a single retry.
  if (await attemptUpdate(args)) return;
  throw new BookingRejectedError(
    "The room system accepted the change but didn't actually apply it. Try again.",
  );
}

export interface CancelBookingArgs {
  room: Room;
  bookingId: string;
  password: string;
}

/** One attempt at validate -> populate -> delete -> confirm. See `attemptUpdate`. */
async function attemptCancel(args: CancelBookingArgs): Promise<boolean> {
  const { room, bookingId, password } = args;
  const session = new ApplianceSession(room.host);
  const validated = await validateBookingAccess(session, room, bookingId, password);

  const populateRes = await session.postForm("populateDelete.action", validated);
  const confirmFields = parseFormFields(populateRes.body);

  const deleteRes = await session.postForm("deleteBooking.action", confirmFields);
  if (!isAcceptedRedirect(deleteRes)) {
    const error = extractFormError(parseFormFields(deleteRes.body));
    throw new BookingRejectedError(
      error ?? `The room system did not confirm the cancellation (HTTP ${deleteRes.status})`,
    );
  }

  // Same reasoning as attemptUpdate: confirm the booking is actually gone
  // rather than trusting the redirect alone. We know its original time
  // range from the validated form, so re-querying that window is enough.
  const start = fromFormDateParts(validated.startDate!, validated.startMonth!, validated.startTime!);
  const end = fromFormDateParts(validated.endDate!, validated.endMonth!, validated.endTime!);
  const raw = await fetchBookings(room.host, start, end);
  return raw.every((b) => String(b.Id) !== bookingId);
}

export async function cancelBooking(args: CancelBookingArgs): Promise<void> {
  if (await attemptCancel(args)) return;
  if (await attemptCancel(args)) return;
  throw new BookingRejectedError(
    "The room system accepted the cancellation but the booking is still there. Try again.",
  );
}
