/**
 * Create and cancel bookings.
 *
 * The appliance has no API for either — both go through the same Struts forms
 * a browser uses, verified live end-to-end in the Phase 0 spike (create a
 * booking, confirm it via `get_bookings`, delete it, confirm it's gone). This
 * module is that spike turned into something the relay can call.
 *
 * Create:
 *   GET  BookingForm.action?display_date=&start_time=&end_time=   (session cookie + field defaults)
 *   POST saveBooking.action                                       (full form, our fields overridden)
 *   -> 302 to GroupView.action means accepted; 200 means rejected, form re-rendered
 *
 * Cancel:
 *   GET  BookingForm.action?booking_id=&display_date=
 *   POST validateBookingPassword.action   (password added)        -> showDeleteButton=true means accepted
 *   POST populateDelete.action            (fields carried forward) -> confirmation page
 *   POST deleteBooking.action             (fields carried forward) -> 302 to GroupView.action means deleted
 *
 * Every POST must carry the *entire* previous form, not just the fields we
 * changed — the appliance rejects a partial body. `ApplianceSession` keeps the
 * cookie; `parseFormFields` + a spread override is what carries the rest.
 */

import { randomBytes } from "node:crypto";
import { ApplianceSession } from "./session.ts";
import { BOOKING_DEFAULTS, extractFormError, parseFormFields, type FormFields } from "./forms.ts";
import { fetchBookings, type RawBooking } from "./roomwizard.ts";
import type { Room } from "./rooms.ts";
import {
  toApplianceDate,
  toApplianceTime,
  toFormDateParts,
  type Instant,
} from "./time.ts";

export class BookingValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BookingValidationError";
  }
}

/** The appliance understood the request and said no — wrong password, etc. */
export class BookingRejectedError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "BookingRejectedError";
  }
}

export interface CreateBookingArgs {
  room: Room;
  start: Instant;
  end: Instant;
  purpose: string;
  hostFirstName: string;
  hostLastName: string;
  /** Generated by the caller if omitted — see `generateBookingPassword`. */
  password: string;
}

export interface CreatedBooking {
  id: string;
  roomId: string;
  start: string;
  end: string;
  purpose: string;
  /**
   * Returned exactly once, here. The relay is stateless and does not keep it;
   * the caller (ultimately the browser) must hold onto this to cancel later.
   * See PLAN.md section 7 on why we generate this ourselves rather than
   * leaving a booking unprotected.
   */
  password: string;
}

/** A booking password strong enough to resist offline guessing. See PLAN.md section 7. */
export function generateBookingPassword(): string {
  return randomBytes(18).toString("base64url");
}

/** Does an appliance response amount to "accepted"? Pure, so it's testable without a live appliance. */
export function isAcceptedRedirect(res: { status: number; location: string | null }): boolean {
  return res.status >= 300 && res.status < 400 && (res.location ?? "").includes("GroupView");
}

export async function createBooking(args: CreateBookingArgs): Promise<CreatedBooking> {
  const { room, start, end, purpose, hostFirstName, hostLastName, password } = args;
  const session = new ApplianceSession(room.host);

  const formRes = await session.get("BookingForm.action", {
    display_date: toApplianceDate(start),
    start_time: toApplianceTime(start),
    end_time: toApplianceTime(end),
  });
  const base = parseFormFields(formRes.body);
  const startParts = toFormDateParts(start);
  const endParts = toFormDateParts(end);

  const submission: FormFields = {
    ...base,
    ...BOOKING_DEFAULTS,
    booking_id: "",
    purpose,
    hostFirstName,
    hostLastName,
    password,
    repeatPassword: password,
    start_time: toApplianceTime(start),
    end_time: toApplianceTime(end),
    startTime: toApplianceTime(start),
    startDate: startParts.day,
    startMonth: startParts.yearMonth,
    endTime: toApplianceTime(end),
    endDate: endParts.day,
    endMonth: endParts.yearMonth,
  };

  const saveRes = await session.postForm("saveBooking.action", submission);

  if (!isAcceptedRedirect(saveRes)) {
    const error = extractFormError(parseFormFields(saveRes.body));
    throw new BookingRejectedError(
      error ?? `The room system did not accept the booking (HTTP ${saveRes.status})`,
    );
  }

  const raw = await fetchBookings(room.host, start, end);
  const created = matchCreatedBooking(raw, start, end, purpose);
  if (!created) {
    // The appliance accepted it (we got the redirect) but we couldn't find it
    // on re-read — e.g. the Connector's eventual-consistency window, or
    // something stranger. Surface this distinctly: it means the room may now
    // actually be booked but we have no id to hand back for cancellation.
    throw new BookingRejectedError(
      "The booking was accepted but could not be confirmed afterwards. Check the room's schedule directly before retrying.",
    );
  }

  return { ...created, roomId: room.id, password };
}

/**
 * Pick the booking we just created out of a room's booking list.
 *
 * The appliance's redirect confirms acceptance but carries no booking id, so
 * re-reading the room is the only way to get one back. Several bookings can
 * share an exact start/end if two were raced in close together (the
 * appliance does nothing to prevent that — see PLAN.md section 6), so an
 * exact purpose match is preferred, falling back to the most recently
 * created. Pure and exported so this tie-breaking can be tested directly
 * against fixtures rather than only against a live appliance.
 */
export function matchCreatedBooking(
  raw: readonly RawBooking[],
  start: Instant,
  end: Instant,
  purpose: string,
): Pick<CreatedBooking, "id" | "start" | "end" | "purpose"> | null {
  const startMs = start.getTime();
  const endMs = end.getTime();

  const candidates = raw.filter((b) => {
    const bs = Date.parse(toIsoish(b.start));
    const be = Date.parse(toIsoish(b.end));
    return bs === startMs && be === endMs;
  });
  if (candidates.length === 0) return null;

  const exact = candidates.find((b) => b.purpose === purpose);
  const chosen =
    exact ??
    candidates.reduce((latest, b) =>
      (b.creationDate ?? "") > (latest.creationDate ?? "") ? b : latest,
    );

  return {
    id: String(chosen.Id),
    start: toIsoish(chosen.start),
    end: toIsoish(chosen.end),
    purpose: chosen.purpose,
  };
}

/** `2026/10/07 14:00:00` -> something `Date.parse` accepts, for a bare equality check. */
export function toIsoish(applianceTimestamp: string): string {
  return applianceTimestamp.replace(/\//g, "-").replace(" ", "T");
}

export interface CancelBookingArgs {
  room: Room;
  bookingId: string;
  password: string;
}

export async function cancelBooking(args: CancelBookingArgs): Promise<void> {
  const { room, bookingId, password } = args;
  const session = new ApplianceSession(room.host);

  const formRes = await session.get("BookingForm.action", { booking_id: bookingId });
  const loaded = parseFormFields(formRes.body);
  if (!loaded.booking_id) {
    throw new BookingValidationError(`No booking ${bookingId} found on ${room.id}`);
  }

  const withPassword: FormFields = { ...loaded, password };
  const validateRes = await session.postForm("validateBookingPassword.action", withPassword);
  const validated = parseFormFields(validateRes.body);
  if (validated.showDeleteButton !== "true") {
    throw new BookingRejectedError("Incorrect booking password");
  }

  const populateRes = await session.postForm("populateDelete.action", validated);
  const confirmFields = parseFormFields(populateRes.body);

  const deleteRes = await session.postForm("deleteBooking.action", confirmFields);
  if (!isAcceptedRedirect(deleteRes)) {
    const error = extractFormError(parseFormFields(deleteRes.body));
    throw new BookingRejectedError(
      error ?? `The room system did not confirm the cancellation (HTTP ${deleteRes.status})`,
    );
  }
}
